export interface DocTopic {
  id: string
  title: string
  description: string
  icon: string
  category: 'basics' | 'tensors' | 'autograd' | 'nn' | 'optimization' | 'advanced' | 'cv' | 'nlp' | 'gan' | 'rl'
  estimatedTime: string
  complexity: 'beginner' | 'intermediate' | 'advanced' | 'expert'
}

export const docTopics: DocTopic[] = [
  {
    id: 'pytorch-intro',
    title: 'Introduction to PyTorch',
    description: 'Core concepts, installation, and ecosystem overview',
    icon: 'rocket',
    category: 'basics',
    estimatedTime: '20 min',
    complexity: 'beginner',
  },
  {
    id: 'tensor-fundamentals',
    title: 'Tensor Fundamentals',
    description: 'Creating, manipulating, and understanding tensor operations',
    icon: 'cube',
    category: 'tensors',
    estimatedTime: '30 min',
    complexity: 'beginner',
  },
  {
    id: 'tensor-broadcasting',
    title: 'Broadcasting & Indexing',
    description: 'Advanced tensor manipulation, broadcasting rules, and indexing techniques',
    icon: 'arrows-out',
    category: 'tensors',
    estimatedTime: '25 min',
    complexity: 'intermediate',
  },
  {
    id: 'autograd-basics',
    title: 'Automatic Differentiation',
    description: 'Understanding autograd, computational graphs, and gradient computation',
    icon: 'git-branch',
    category: 'autograd',
    estimatedTime: '35 min',
    complexity: 'intermediate',
  },
  {
    id: 'nn-module',
    title: 'Neural Network Modules',
    description: 'Building blocks: nn.Module, layers, activation functions, and architectures',
    icon: 'network',
    category: 'nn',
    estimatedTime: '40 min',
    complexity: 'intermediate',
  },
  {
    id: 'cnn-architectures',
    title: 'Convolutional Neural Networks',
    description: 'Conv layers, pooling, batch normalization, and CNN architectures',
    icon: 'grid-four',
    category: 'nn',
    estimatedTime: '45 min',
    complexity: 'intermediate',
  },
  {
    id: 'rnn-lstm',
    title: 'Recurrent Networks & LSTMs',
    description: 'Sequential data processing, RNNs, LSTMs, and GRUs',
    icon: 'arrows-clockwise',
    category: 'nn',
    estimatedTime: '50 min',
    complexity: 'advanced',
  },
  {
    id: 'transformers',
    title: 'Attention & Transformers',
    description: 'Self-attention mechanisms, multi-head attention, and transformer architecture',
    icon: 'star',
    category: 'nn',
    estimatedTime: '60 min',
    complexity: 'advanced',
  },
  {
    id: 'loss-functions',
    title: 'Loss Functions',
    description: 'MSE, Cross-Entropy, Custom losses, and choosing the right loss',
    icon: 'target',
    category: 'optimization',
    estimatedTime: '30 min',
    complexity: 'intermediate',
  },
  {
    id: 'optimizers',
    title: 'Optimization Algorithms',
    description: 'SGD, Adam, AdamW, learning rate schedules, and optimizer selection',
    icon: 'chart-line-up',
    category: 'optimization',
    estimatedTime: '35 min',
    complexity: 'intermediate',
  },
  {
    id: 'training-loop',
    title: 'Training Loop Architecture',
    description: 'Best practices for training, validation, checkpointing, and monitoring',
    icon: 'repeat',
    category: 'optimization',
    estimatedTime: '40 min',
    complexity: 'intermediate',
  },
  {
    id: 'custom-autograd',
    title: 'Custom Autograd Functions',
    description: 'Implementing custom backward passes and gradient manipulation',
    icon: 'function',
    category: 'advanced',
    estimatedTime: '45 min',
    complexity: 'advanced',
  },
  {
    id: 'distributed-training',
    title: 'Distributed Training',
    description: 'Data parallelism, model parallelism, and multi-GPU training',
    icon: 'devices',
    category: 'advanced',
    estimatedTime: '55 min',
    complexity: 'expert',
  },
  {
    id: 'model-optimization',
    title: 'Model Optimization & Deployment',
    description: 'Quantization, pruning, ONNX export, and production deployment',
    icon: 'lightning',
    category: 'advanced',
    estimatedTime: '50 min',
    complexity: 'expert',
  },
  {
    id: 'cv-fundamentals',
    title: 'Computer Vision Fundamentals',
    description: 'Image preprocessing, data augmentation, and CV pipelines',
    icon: 'eye',
    category: 'cv',
    estimatedTime: '40 min',
    complexity: 'intermediate',
  },
  {
    id: 'object-detection',
    title: 'Object Detection',
    description: 'YOLO, R-CNN, Faster R-CNN, and real-time detection systems',
    icon: 'selection',
    category: 'cv',
    estimatedTime: '55 min',
    complexity: 'advanced',
  },
  {
    id: 'image-segmentation',
    title: 'Image Segmentation',
    description: 'U-Net, Mask R-CNN, semantic and instance segmentation',
    icon: 'puzzle-piece',
    category: 'cv',
    estimatedTime: '50 min',
    complexity: 'advanced',
  },
  {
    id: 'pose-estimation',
    title: 'Pose Estimation & Tracking',
    description: 'Human pose estimation, keypoint detection, and motion tracking',
    icon: 'person-arms-spread',
    category: 'cv',
    estimatedTime: '45 min',
    complexity: 'advanced',
  },
  {
    id: 'gan-basics',
    title: 'Generative Adversarial Networks',
    description: 'GAN architecture, generator-discriminator dynamics, and training tricks',
    icon: 'image',
    category: 'gan',
    estimatedTime: '60 min',
    complexity: 'advanced',
  },
  {
    id: 'dcgan',
    title: 'Deep Convolutional GANs',
    description: 'DCGAN architecture, stable training, and image generation',
    icon: 'images',
    category: 'gan',
    estimatedTime: '50 min',
    complexity: 'advanced',
  },
  {
    id: 'stylegan',
    title: 'StyleGAN & Advanced GANs',
    description: 'StyleGAN, Progressive GANs, conditional GANs, and style transfer',
    icon: 'palette',
    category: 'gan',
    estimatedTime: '65 min',
    complexity: 'expert',
  },
  {
    id: 'wgan',
    title: 'Wasserstein GANs & Variants',
    description: 'WGAN, WGAN-GP, improved training stability and metrics',
    icon: 'waves',
    category: 'gan',
    estimatedTime: '55 min',
    complexity: 'expert',
  },
  {
    id: 'diffusion-models',
    title: 'Diffusion Models',
    description: 'DDPM, denoising diffusion, and modern generative models',
    icon: 'spiral',
    category: 'gan',
    estimatedTime: '70 min',
    complexity: 'expert',
  },
  {
    id: 'rl-basics',
    title: 'Reinforcement Learning Basics',
    description: 'MDP, rewards, policies, value functions, and Q-learning',
    icon: 'game-controller',
    category: 'rl',
    estimatedTime: '50 min',
    complexity: 'advanced',
  },
  {
    id: 'dqn',
    title: 'Deep Q-Networks (DQN)',
    description: 'Experience replay, target networks, and DQN variants',
    icon: 'target',
    category: 'rl',
    estimatedTime: '55 min',
    complexity: 'advanced',
  },
  {
    id: 'policy-gradient',
    title: 'Policy Gradient Methods',
    description: 'REINFORCE, actor-critic, A2C, and A3C algorithms',
    icon: 'chart-line',
    category: 'rl',
    estimatedTime: '60 min',
    complexity: 'expert',
  },
  {
    id: 'ppo-trpo',
    title: 'PPO & TRPO',
    description: 'Proximal Policy Optimization and Trust Region methods',
    icon: 'shield-check',
    category: 'rl',
    estimatedTime: '65 min',
    complexity: 'expert',
  },
  {
    id: 'model-based-rl',
    title: 'Model-Based RL',
    description: 'World models, planning, and model-based reinforcement learning',
    icon: 'globe',
    category: 'rl',
    estimatedTime: '70 min',
    complexity: 'expert',
  },
  {
    id: 'word-embeddings',
    title: 'Word Embeddings & Language Models',
    description: 'Word2Vec, GloVe, embeddings, and language modeling',
    icon: 'text-aa',
    category: 'nlp',
    estimatedTime: '45 min',
    complexity: 'intermediate',
  },
  {
    id: 'seq2seq',
    title: 'Sequence-to-Sequence Models',
    description: 'Encoder-decoder, attention mechanisms, and seq2seq applications',
    icon: 'arrows-left-right',
    category: 'nlp',
    estimatedTime: '50 min',
    complexity: 'advanced',
  },
  {
    id: 'bert-transformers',
    title: 'BERT & Modern Transformers',
    description: 'BERT, GPT, T5, fine-tuning, and transfer learning',
    icon: 'robot',
    category: 'nlp',
    estimatedTime: '65 min',
    complexity: 'expert',
  },
  // ─── Advanced / performance (added in Phase 2) ───
  {
    id: 'torch-compile',
    title: 'torch.compile & Graph Capture',
    description: 'TorchDynamo, Inductor, TorchScript, FX — turn Python into a fused graph',
    icon: 'lightning',
    category: 'advanced',
    estimatedTime: '30 min',
    complexity: 'advanced',
  },
  {
    id: 'hooks',
    title: 'Hooks & Introspection',
    description: 'Forward/backward hooks to inspect activations, extract features, and rewrite gradients',
    icon: 'magnifying-glass',
    category: 'advanced',
    estimatedTime: '25 min',
    complexity: 'intermediate',
  },
  {
    id: 'gradient-checkpointing',
    title: 'Gradient Checkpointing',
    description: 'Trade compute for memory: recompute activations during backward to fit bigger models',
    icon: 'floppy-disk',
    category: 'advanced',
    estimatedTime: '25 min',
    complexity: 'advanced',
  },
  {
    id: 'mixed-precision',
    title: 'Mixed Precision (AMP)',
    description: 'autocast + GradScaler for 1.5–2× faster training with ~50% less memory',
    icon: 'gauge',
    category: 'optimization',
    estimatedTime: '30 min',
    complexity: 'intermediate',
  },
  {
    id: 'ddp',
    title: 'DistributedDataParallel (DDP)',
    description: 'One process per GPU, all-reduce gradients — the standard way to go multi-GPU',
    icon: 'graph',
    category: 'advanced',
    estimatedTime: '40 min',
    complexity: 'advanced',
  },
  {
    id: 'fsdp',
    title: 'Fully Sharded Data Parallel (FSDP)',
    description: 'Shard parameters, grads, and optimizer state across GPUs to fit much bigger models',
    icon: 'squares-four',
    category: 'advanced',
    estimatedTime: '40 min',
    complexity: 'expert',
  },
  {
    id: 'profiler',
    title: 'Profiling & Performance',
    description: 'torch.profiler traces — find the slow layer, overlap data loading, shrink idle gaps',
    icon: 'chart-line',
    category: 'advanced',
    estimatedTime: '30 min',
    complexity: 'intermediate',
  },
  {
    id: 'distributions-reparam',
    title: 'Distributions & the Reparameterisation Trick',
    description: 'torch.distributions, sample vs rsample, log_prob — the building block of VAEs and policy gradients',
    icon: 'shuffle',
    category: 'advanced',
    estimatedTime: '35 min',
    complexity: 'advanced',
  },
  {
    id: 'vmap-func',
    title: 'torch.func & vmap',
    description: 'Functional transforms: vmap auto-batches, grad/jacrev/jacfwd/hessian compose cleanly',
    icon: 'stack',
    category: 'advanced',
    estimatedTime: '30 min',
    complexity: 'advanced',
  },
  {
    id: 'weight-init',
    title: 'Weight Initialisation',
    description: 'Why zeros fail, why small-normal vanishes, and why Kaiming / Xavier are the sane defaults',
    icon: 'seed',
    category: 'nn',
    estimatedTime: '20 min',
    complexity: 'intermediate',
  },
  {
    id: 'quantization',
    title: 'Quantisation',
    description: 'int8 weights and activations: 4× smaller, 2–3× faster CPU inference',
    icon: 'archive',
    category: 'advanced',
    estimatedTime: '35 min',
    complexity: 'advanced',
  },
  {
    id: 'pruning',
    title: 'Pruning',
    description: 'Zero out the smallest-magnitude weights, briefly retrain — smaller models with near-zero accuracy loss',
    icon: 'scissors',
    category: 'advanced',
    estimatedTime: '25 min',
    complexity: 'advanced',
  },
]

export const docCategories = [
  { id: 'basics', label: 'Basics', color: 'primary' },
  { id: 'tensors', label: 'Tensors', color: 'secondary' },
  { id: 'autograd', label: 'Autograd', color: 'coral' },
  { id: 'nn', label: 'Neural Networks', color: 'violet' },
  { id: 'optimization', label: 'Optimization', color: 'cyan' },
  { id: 'cv', label: 'Computer Vision', color: 'lime' },
  { id: 'gan', label: 'GANs & Generation', color: 'pink' },
  { id: 'rl', label: 'Reinforcement Learning', color: 'orange' },
  { id: 'nlp', label: 'NLP & Transformers', color: 'violet' },
  { id: 'advanced', label: 'Advanced Topics', color: 'coral' },
] as const
